### ISSUE TITLE
Výběr vedoucího týmu

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#1]
Napiste kazdy, kdo si myslite, ze by mel byt projektovym manazerem, nebo proc byste to meli byt prave vy. Napriklad:
- Co vas bavi
- Zkusenosti
- Co vas na tom nejvic laka apod. 

Prodejte se pro sve kolegy nebo podporte sve favority. Milestone mame nastaveny do 22.2.2015, takze poprosim vsechny, aby se do te doby vyjadrili.

**Comment by S1LL** [comment]
Já si myslím, že ses toho ujal aktivně :). Pokud sám chceš být, a Tomáš mi říkal, že asi jo, tak proč ne. :+1:

**Comment by jlorenc01** [comment]
Mluvili jsme o tom a prý bys o to měl zájem. Tak bych to tak nechal. Za mě tedy Filip.

**Comment by xlenga01** [comment]
Filip or feed!!!!

**Comment by azuritus** [comment]
Filipe, iniciativně jsi se toho zhostil a myslím, že je výborný nápad abys v tom i nadále pokračoval :)

**Comment by KratochvilJiri** [comment]
Zdravim,
tak vidim, ze vsichni maji obrovsky zajem o managera...:]. Ja proti Filipovi take nic nemam urcite mu to pujde dobre. Co se me touhy po teto funkci tyka.. Jestli tohle mam brat jako hlasovani, tak uz je asi stejne rozhodnuto. Pokud vsak Filip nechce tuto pozici delat klidne bych to zkusil. Zkusenosti zadne nemam a ani nevim, co je presna napln prace (nejake konkretni techniky atd), ale tak co se da delat to typuji, ze vetsina. Jinak ocekaval jsem, ze se najde aspon jeden fanaticky manager v tymu, ktery po tomto postu skoci a asi nic.. Takze ve zkratce: pokud by nikdo nejevil vetsi zajem, rad si to vyzkousim :].

**Comment by FilipMatys** [comment]
Skvele, tak prvni zajemce :) Jsem rad, ze jste projevili svuj nazor a probehlo zde hlasovani, ale osobne jsem se o post vedouciho tymu nehlasil. Osobne se priklanim k tomu, aby byl zvolen clovek, ktery o to ma zajem. Sebe jsem bral spise jako posledni moznost. 

Dal bych tedy jeste prostor ostatnim pro vyjadreni do zitrejsiho vecera a potom bysme to uzavreli.

Jeste odpoved k poslednimu prispevku:
Jirku osobne znam a jde o vudci osobnost. Ja jsem spise pasivni clovek, takze bude urcite lepsi volba.

Pokud nejake zkusenosti mam, at uz z firmy nebo s nastroji, tak se o ne rad s vedoucim podelim.

**Comment by KratochvilJiri** [comment]
Tak to teda diky :D. Ja se jako vudci osobnost moc nevidim :)). Ale o to tu podle me ani tolik nejde v kazdemu cloveku to je. Urcite jste se vsichni nebo vetsina potkali s Mgr. Kaláškákem na nějakých soft skills. Nám vyprávěl příběhy o tom jak před xx lety byl, tak pasivni a bázlivý introvert, že se pomalu bál pozdravit souseda a teď je z neho top manager :). 

Jinak jeste me napadlo, ze pokud je tak velky zajem, muzem si to klidne rozdelit a kazdy si muze odmanagovat urcitou cast, at si to vyzkousi kazdy. Ale mozna je to trosku prace navic..

**Comment by ghost** [comment]
Jelikož já jsem se k vám přidal do počtu a bohužel vás moc neznám, tak bych spise nechal volbu managera na vas.
Co se tyce me, moc se v managerovi jako roli nevidim...

**Comment by andreamarcelyova** [comment]
Takze to vyzera ze asi nikto iny o poziciu manazera zaujem nema, ja tiez nie, tak asi bude fajn ked sa toho zhosti niekto koho to laka, teda Jiri. :)

**Comment by FilipMatys** [comment]
Je rozhodnuto, vedoucim tymu se stava Jiri Kratochvil, proto zaviram. Dekuji vsem za vyjadreni
