### ISSUE TITLE
Logování práce

### ISSUE THREAD

**Issue by KratochvilJiri** [FilipMatys/MPR2015#10]
Vytvoření a inicializace dokumentu na Google Docs, kde bude každý individuálně a průběžně zapisovat odvedenou práci na projektu.

**Comment by KratochvilJiri** [comment]
Dokument jsem vytvořil a rozslal vám emaily s pozvánkami. Pro jistot, že by email někomu nedorazil přidávám můj komentář společně s odkazem.

Zdravím,
připravil jsem google doc pro logování práce. Barviček se nelekejte, snažil jsem se to aspoň trošku zpřehlednit. Pokud bude mít někdo nápad a chuť to vylepšit klidně to upravte, ale myslím, že pro naše účely to poslouží.

Jakmile dokončíte práci na nějakém úkolu nezapomeňte si ho zalogovat. Je to jako v práci, kdo si nic nezaloguje, nakonci měsíce nic nedostane (bohužel vy můžete v tomto případě dostat leda víc práce). Snažte se to brát svědomitě a odhadnout skutečný čas strávený na úkole a uvažujte i prokrastinaci atd., ačkoliv pevně věřím, že pracujete vždy na 100%.

Jen pro shrnutí. Logování je důležité ze dvou důvodu. Musíme nakonci vytvořit celkovou cenu aplikace tzn. na kolik nás aplikace přišla. To bez odpracovaných hodin nejde.
Druhý důvod je přehled o odpracovaných hodinách tzn. pokud někdo bude mít přiliš práce a jiní naopak nedostatek, budeme to řešit.

https://docs.google.com/spreadsheets/d/1P1HpAjFapfD9Eb9bvt33rWUlY59CNJf43b5ym-edXKU/edit?usp=sharing_eid&invite=CNn2s-sF

**Comment by FilipMatys** [comment]
Jeste doplnim. Pridal jsem do sheetu trochu logiky, ktera automaticky pocita sumu odpracovanych hodin a pocita vyslednou cenu. 

Aby vse fungovalo, tak prosim zadavejte hodiny jako desetinna cisla s carkou jako oddelovacem. 

Dekuji
