### ISSUE TITLE
Detail konference: Description - maximální délka

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#101]
Maximální délka popisu je nyní 255 znaků, což je velmi málo. Poprosím délku zvýšit ideálně na LONGTEXT.

**Comment by jlorenc01** [comment]
Upravil jsem i ostatní atributy description apod. Maximálně šla zadat délka 4 000, tak jsem omezení na délku odstranil. Dle chybového hlášení při pokusu zadat délku více než 4 000 by při nevyplnění pole max length mělo být možné uložit i delší řetězec.
