### ISSUE TITLE
Detail konference: Set as active/closed nefunguje

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#103]
Po stisku tlačítka musí dojít rovnou k uložení, nikoliv k nastavení na pozadí.

Aktuálně funguje následovně:
Po stisknutí tlačítka Set as active se tlačítko změní na Set as closed. Po uložení se stav uloží (Špatně)

Je potřeba:
Po stisknutí tlačítka Set as active dojde k uložení do stavu Active

**Comment by azuritus** [comment]
Opraveno.
