### ISSUE TITLE
Detail účasti - Zobrazovat pouze názvy souborů s odkazem

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#105]
Pokud se nahraje obrázek, tak jeho zobrazení je nekorektní. Vyřešit odkazem

**Comment by azuritus** [comment]
Náhled odstraněn, pro zobrazování názvů souborů by je bylo potřeba ukládat, což je na změnu modelu. Proto nechávám zatím otevřené.

**Comment by FilipMatys** [comment]
Ok
