### ISSUE TITLE
Uživatel: Firma - Nezobrazovat tlačítko participations, pokud je přihlášeným uživatelem firma

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#107]
Tlačítko Participations slouží pouze pro FIT (admin a kontaktní osoba) jako odkaz na účasti firmy. Firma jako taková však nemá do seznamu účastí přistup. Své účasti vidí pouze na své nastěnce.

**Comment by azuritus** [comment]
Upraveno.

**Comment by FilipMatys** [comment]
Toto zavírám, je však potřeba doupravit v #110
