### ISSUE TITLE
Uživatel: Vyplnění hesla

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#108]
1) Při načtení detailu uživatele by se nemělo načítat heslo
2) Při uložení by se mělo kontrolovat zadání hesla. V případě, kdy není zadané, tak umožnit uložení (bez změny hesla). Nemělo by být totiž nutné při úpravě uživatele vždy zadávat heslo.

**Comment by azuritus** [comment]
Upraveno.
