### ISSUE TITLE
Zápis z 1. externí schůze (se zákazníkem)

### ISSUE THREAD

**Issue by KratochvilJiri** [FilipMatys/MPR2015#11]
Poprosil bych tě, aby jsi vypracovala zápis z dnešní schůzky se zákazníkem. 

Šablonu najdeš na stránkách MPR. Můžes se inspirovat i úvodní zprávou z naší schůzky, kterou jsem napsal. Tím nechci tvrdit, že tato zpráva je naprosto správně. Použij ji spíš v případě, že nebudeš vědět o čem psát, ale je to jednoduché, takže určitě nebude problém.

Byl bych rád, kdyby jsi to vypracovala do zítřejšího večera tzn. 3.3.2015. Samozřejmě čím dříve na tom začneš pracovat, tím se ti to bude psát snadněji. 

Výsledný dokument pojmenuj, tak jak to říkal na dnešní schůzce a umísti na google drive (odkaz na wiki) do složky schuze-zaznamy/externi. Ja na to potom ještě mrknu.

V připadě jakýchkoliv nejasností mne kontaktuj.

**Comment by andreamarcelyova** [comment]
Ok, dnes pobede/navecer to napisem a hodim to tam.

**Comment by KratochvilJiri** [comment]
Vypracováno, schváleno. Dobrá práce! Dokument můžete nalézt v dokumentovém skladu.
