### ISSUE TITLE
Uživatel - Tlačítko Participations

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#110]
Bohužel nyní blbne zobrazení, zkusím napsat přesné stavy. Zobrazuje se pouze tehdy, když:
- Role je "Company"
- Uživatel je již vytvořen (nejedná se o jeho tvorbu)
- Přihlášeny uživatel není typu "Company"

**Comment by azuritus** [comment]
Opraveno, snad už jsem to pobral správně.

**Comment by FilipMatys** [comment]
Děkuji
