### ISSUE TITLE
Dashboard: Admin/Kontaktní osoba - Nezobrazují se Participation* dlaždice

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#111]

**Comment by FilipMatys** [comment]
Nejedná se jen o odkaz na Participation, ale i dlaždice, které nesou parametry.

**Comment by azuritus** [comment]
Přísahal bych, že mě to fungovalo i před tím, každopádně by to už melo být opravené.

**Comment by FilipMatys** [comment]
V pohodě ;)
