### ISSUE TITLE
Účast firmy na konferenci musí být unikátní

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#113]
Momentálně lze vytvořit pro jednu firmu více účastí (Skrze okno Participations), což je špatně

**Comment by azuritus** [comment]
Doplněn složený unikátní index na Firmu a Konferenci. Pokud už však existují špatná data, bude je nutné před nasazením opravit / odstranit.

**Comment by FilipMatys** [comment]
Počítám s tím, děkuji
