### ISSUE TITLE
Detail konference: Submit payment

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#118]
Zobrazuje se pouze tehdy, pokud je účast ve stavu Signed a dodat implementaci tlačítka (Po stisknutí dojde ihned k uložení)

**Comment by xlenga01** [comment]
Melo by byt vyreseno

**Comment by FilipMatys** [comment]
Mělo, nebo je? Pokud ano, tak Resolved! Potřebuju se v tom vyznat
