### ISSUE TITLE
Participation: Workflow

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#119]
- Registered
  -- Při vytvoření
- Approved
  -- Po přiřazení kontaktní osoby, takže při Assign to me a při vytvoření uživatele firma skrze tlačítko Save and assign to me
- Contract signed
  -- Po uložení materiálu Contract
- Canceled
  -- Po kliknutí na tlačítko Cancel participation
- Complete
  -- Po uzavření přiřazené konference

Pokud najdete chybu nebo nesrovnalosti, tak mi napište.

**Comment by azuritus** [comment]
Implementováno.
