### ISSUE TITLE
Seznámení se s LightSwitch

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#12]
Poprosim cleny implementacniho tymu, aby se seznamili s frameworkem LightSwitch.

O link na tutorial poprosim Pavla.

Dekuji

**Comment by FilipMatys** [comment]
Link jsem pravdepodobne nasel, takze prikladam:
http://www.codeproject.com/Articles/746157/An-End-To-End-Visual-Studio-LightSwitch-HTML

**Comment by FilipMatys** [comment]
Velice doporucuji shlednout nasledujici tri videa, pokud Vam neco z vyse zmineneho linku neni jasne:
https://www.youtube.com/user/UCJAEjqy76xRdQzTn45C/search?query=Light

**Comment by FilipMatys** [comment]
Jeste mrknete zde. Probira se tu prihlasovani. Samozrejme neni nutne do pristi schuze, jedna se o narocnejsi priklad:
http://blogs.msdn.com/b/lightswitch/archive/2013/03/18/signed-in-part-1-introduction-andy-kung.aspx

**Comment by FilipMatys** [comment]
Lokalizace
https://msdn.microsoft.com/cs-cz/library/xx130603.aspx

**Comment by KratochvilJiri** [comment]
Doufám, že jste již všichni seznámeni. Zavirám tento úkol. Pokud by někdo zpětně hledal výše zmíněné odkazy. Issues -> closed.
