### ISSUE TITLE
Conference: Workflow

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#120]
Mám implementační dotaz s navazujícím issue.

Předpokládám, že konference bude ve třech stavech:
- Inactive
- Active
- Closed, jelikož uzavřenou konferenci by nemělo jít dostat zase do stavu Active

Z toho mi vyplývá, že je potřeba Active: Bool změnit na výčtový typ.

Poprosím o vyjádření a následně o implementaci. díky.

**Comment by FilipMatys** [comment]
Poprosím o implementaci

**Comment by azuritus** [comment]
Implementováno.
