### ISSUE TITLE
Nelze vytvořit konferenci a nastavit ji jako aktivní

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#125]
Nelze vytvořit konferenci, hlásí "The field Active is required".

Zmizel panel nástrojů, tedy nelze uložit a nastavit jako aktivní a zároveň nelze Set as active/Set as closed. Panel nemá být správně viditelný pouze tehdy, pokud je stav Closed (V tu chvíli totiž nedává smysl)

**Comment by azuritus** [comment]
Opraveno.
