### ISSUE TITLE
Firma: Tlačítko Participate na detailu účasti nefunguje

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#126]
Hlásí:
Cannot read property 'Company' of undefined

**Comment by azuritus** [comment]
Nejspíš to souvisí s #124 když se nedotáhne info o firmě, nebude fungovat ani tohle tlačítko, které informaci využívá.

**Comment by azuritus** [comment]
Opraveno.

**Comment by FilipMatys** [comment]
Děkuji

**Comment by azuritus** [comment]
Opraveno.
