### ISSUE TITLE
Zpráva z 1. schůze programového týmu

### ISSUE THREAD

**Issue by KratochvilJiri** [FilipMatys/MPR2015#13]
Vypracování zprávy z 1. schůze programového týmu.

**Comment by xlenga01** [comment]
Zprava vypracovana a ulozena ve skladu dokumentu.

**Comment by FilipMatys** [comment]
Chapu to dobre, ze se jedna o ten textak?

**Comment by xlenga01** [comment]
Vskutku.

**Comment by KratochvilJiri** [comment]
Po přepracování už to vypadá trošku líp, ale ma to jeste své mouchy. 
1. Dopln do nazvu souboru datum a cislo verze, tak jak je to u vsech dokumentu 
2. Obsah by mel byt na zvlastni strance  
3. Zkratku n.l. tam není potřeba psát, myslim, že každý ví o který letopočet se jedná, takže je to zbytečné 
4. Nadpisy jednotlivych kapitol by mely byt stejnou velikosti pisma 
5. Formatovani textu neni nic moc, zkus to trosku vylepsit 
6. Kdyz pouzivas nejaky nazev SW/nastroje cehokoliv, zkus drzet jednotny nazev napr nepouzivat gitHub a o dva radky nize Git nebo windows azur a jinde Windows Azure 
7. Nekombinuj české a anglické slova pokud to neni nutne potreba viz "navrzeno by hrabe00” 
8. Zkus si po sobe text alespon jednou precist, vim ze nikdo neni neomylny a kazdemu se nejake chyby obcas vyskytnou, ale bylo by dobre opravit alespon ty do oci bijici jako "viz. víše" či na "zchůzi” 
9. Vždycky, když vypracuješ/přepracujes nejaky dokument dej to nejakym zpusobem vedet, nejlepe na gitHub, moji povinnosti neni kazdou hodinu kontrolovat uloziste s dokumentaci, jestli nahodou nekdo neprovedl zmenu. Kdyz tohle opravis mohlo by to byt fajn. 
   Diky.
