### ISSUE TITLE
Dokument - Úvodní studie

### ISSUE THREAD

**Issue by KratochvilJiri** [FilipMatys/MPR2015#14]
Vypracování dokumentu Úvodní studie do 8.3.2015. Šablona k tomuto dokumentu je v zadání. Dokonce lze nalézt (po kliknutí na "Úvodní studie" v tabulce požadovaných dokumentů) vypracovaný dokument na jinou aplikaci.

Z poslední schůzky s asistentem jsem pochopil, že dokument je hlavně pro nás, abychom zase trošku blíže vymezili funkce, cíle, výstupy systému. Podle toho vypracovaného vzoru a informací, které momentálně máme by to neměl být problém. Osobně jsem zvědav, co nám na dokument řekne asistent, protože jeho pohled na mě působí, že jsou tyto šablony trošku mimo. Kdyby jsi měla nějaké otázky, nejasnosti, ozvi se.

**Comment by andreamarcelyova** [comment]
Ok, cez vikend vypracujem, keby nieco ozvem sa

**Comment by andreamarcelyova** [comment]
Nahrala som dokument na drive, pisala som to viac menej podla toho vypracovaneho vzoru na mpr strankach, niektore veci mi tam uplne nedavali zmysel, tiez som zvedava co na to povie asistent... :)

**Comment by KratochvilJiri** [comment]
Uzavřeno - schváleno.
