### ISSUE TITLE
Dokument - Specifikace požadavků

### ISSUE THREAD

**Issue by KratochvilJiri** [FilipMatys/MPR2015#15]
Nastuduj dokument Specifikace požadavků udělej si představu o tom jak by to mělo cca vypadat. V zadání je šablona. Více bych se věnoval té, která je přímo na stránkách nikoliv v souboru .doc.

Pokud nebudeš mít problém můžeš to rovnou napsat. Jestli si nebudeš vědět rady, sedneme nad tím po neděli ve více lidech a dáme to dohromady. V případě nejasností mě kontaktuj.

Dokonce týdne vypracuj/nastuduj alespon základ/kostru/obecné věci/co by mělo být obsaženo v jednotlivých bodech dokumentu.

**Comment by S1LL** [comment]
jojo, beru na vědomí, zítra se na to kouknu

**Comment by S1LL** [comment]
@KratochvilJiri nahrál sem do skladu, co jsem dneska stihl. Kouknul by ses na to, jestli nejsem úplně mimo?

**Comment by KratochvilJiri** [comment]
Super, mrknu na to a dam vědět.

**Comment by KratochvilJiri** [comment]
Prošel jsem to a udělal si nějaké poznámky. Napiš mi na Skypu až budeš mít čás, probereme to.

**Comment by KratochvilJiri** [comment]
Schváleno, uzavřeno.
