### ISSUE TITLE
Nasazení projektu pro testování

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#16]
Pro účely testování aplikace bude probíhat nasazení na online platformu. Na této platformě bude umožněno všem testujícím aplikaci vyzkoušet a testovat nově vytvořenou funkcionalitu. 

Nabízí se dvě možnosti:
Windows Azure
- kdysi existovala freemium verze, která ale umožňovala životnost aplikace pouze 24hodin od nasazení, nyní je možné pořídit pouze měsíční trial verzi a poté běh aplikace platit.
  AppHarbor
- umožňuje nasazení LightSwitch aplikace zadarmo

Nejdříve bude otestován AppHarbor. V případě, že nebude dostačovat, tak využijeme měsíční trial od Windows Azure

**Comment by KratochvilJiri** [comment]
Bylo by fajn to rozjet. Ja totiž například nemůžu monitorovat výslednou práci jelikož mám Mac. Verze bychom mohli aktualizovat v nějakých periodách a nebo já se toho klidně můžu ujmout.

Filipe zkusíš to tedy rozjet jak jsme se bavili?

**Comment by FilipMatys** [comment]
Jdu na to

**Comment by FilipMatys** [comment]
https://excellenttest.azurewebsites.net/htmlclient

**Comment by FilipMatys** [comment]
Údaje pro přihlášení na testovací instanci jsou v datovém skladu ve složce testing

**Comment by KratochvilJiri** [comment]
Supr. Aktualizace budeme provádět dle potřeby.
