### ISSUE TITLE
2. schůze týmu

### ISSUE THREAD

**Issue by KratochvilJiri** [FilipMatys/MPR2015#17]
Pomalu se rysuje specifikace požadavků, ale je nutno prodiskutovat několik věcí společně s programátorskou částí týmu.

Na schůzi nutně nevyžaduji účást @andreamarcelyova, ale pokud se zučastní a přispěje bude to jenom dobře.

Plán:
1. Upřesnění specifikace požadavků

Termíny: 
http://doodle.com/ixnrt72fnq7zqkeu#table

**Comment by S1LL** [comment]
Právě jsem nahrál verzi, která je více méně připravená k větší diskuzi. Prosím, přečtěte si důkladně dokument ve verzi 1.1 a udělejte si poznámky. Věci co jsem nevěděl nebo nejsou kompletní jsou v dokumentu červeně, těm prosím věnujte zvýšenou pozornost. Samozřejmě můžeme měnit vše... Pokud někoho něco napadne k poslední kapitole dokumentu budu jenom rád.

**Comment by KratochvilJiri** [comment]
Schůze bude ve středu v 11:30, predbezne v konference c.1 - knihovna, ale jeste to potvrdím az ji zamluvim.

**Comment by andreamarcelyova** [comment]
Pridem aj ja, chcem zostat  v obraze :)

**Comment by KratochvilJiri** [comment]
Na zítra 11:30 je zamluvena konferencni mistnost c.2. Zápis ze schůze vypracuje @Lorry1

**Comment by KratochvilJiri** [comment]
Schůze proběhla dle předpokladů. Zápis ve skladu dokumentů.
