### ISSUE TITLE
Dokument - Plán projektu

### ISSUE THREAD

**Issue by KratochvilJiri** [FilipMatys/MPR2015#19]
Vypracuj dokument plán projektu. Šablonu najdeš na stránkách MPR. Hlavní body jsou:
1. Úvod
2. Použitý model životního cyklu.
3. Složení a role týmu - kdo je za co globálně zodpovědný -- hlavní manažer, vedoucí pro jednotlivé etapy.
4. Harmonogram - tabulka s uvedením etap a jejich významných částí, dob jejich trvání, milníky (finální verze dokumentů apod.) s termíny, datumy oponentur, k činnostem přiřazené role, osoby, náklady. Musí být vytvořený v MS Projectu.
5. Způsob předání - jak bude produkt předveden a předán zákazníkovi.

Doufám, že nebude problém ta šablona mi připadala vcelku jasná, co jsem ji procházel. V MS Project ti to také šlo! Kdyby jsi měl nějaké problémy/nejasnosti ozvi se a probereme to. Měl by jsi to dokončit dokonce týdne - tím myslím verzi 1.0 bez schválení. Samozřejmě čim dříve tím lépe. Dokument MS Project ze cvičení je nasdílení ve složce s Dokumenty-MPR na Google drive.

**Comment by ghost** [comment]
Ok, beru na vedomi. Nejdrive se stihnu na to podivat v utery.

**Comment by KratochvilJiri** [comment]
Schváleno, uzavřeno.
