### ISSUE TITLE
Komunikační nástroje

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#2]

**Comment by FilipMatys** [comment]
Sprava issues, milniku a diskuze tymu: www.github.com

Domlouvani terminu: www.doodle.com

**Comment by FilipMatys** [comment]
Dokumentace: wiki od GitHub
https://github.com/FilipMatys/MPR2015/wiki

**Comment by KratochvilJiri** [comment]
Github pro issues, milniky souhlasim a pravdepodobne i pro diskuzi tymu ikdyz nevim jestli je zrovna toto ten nejlepsi nastroj pro diskuze. Na druhou stranu je fajn to mit na jednom miste.
Napadl me jeste facebook. Jen zalozit skupinu pro rychlou domluvu atd.. Vim, je to tezce amaterske a pred nejakou komisi bysme to nemohli ani zminit, protoze by nas ihned ukamenovali :D. Na druhou stranu typuji, ze ho ma kazdy minimalne kvuli FIT skupine a diva se tam pomerne casto, takze pokud by slo o nejake spamerske diskuze slo by to...ale mozna bych se tomu radeji vyhnul. 
Doodle neznam, ale na ty terminy to vypada fajn. 
Za stezejni komunikaci povazuji osobni schuzky pripadne nejake videokonference (skype, hangout), kdyz nebude schuzka mozna pripadne zbytecna. 
Dale si myslim, ze minimalne manager by mel mit telefon na vsechny cleny tymu. Totez clenove, kteri budou pracovat spolecne na urcite problematice.

**Comment by FilipMatys** [comment]
Souhlasim, ale k FB se stavim celkem pesimisticky. Osobne bych se tomu radeji vyhnul, protoze by to nebylo oddelene od prace a nechtel bych neco resit, zatimco mi do toho chodi upozorneni o festivalech, kdo mi co lajkl a podobne.

Kazdopadne to ma pomerne velkou komunikacni silu, takze branit se tomu nebudu.

Schuzky take vidim jako stezejni, jen mam strach z toho, abychom se mohli v klidu sejit. Nejhure muzeme prohodit par slov na prednasce, to mi ale neprijde efektivni a predpokladam, ze bude vetsina souhlasit. Takze schuzky povinne.

Telefon rozhodne souhlasim.

**Comment by KratochvilJiri** [comment]
Ano, mam vicemene stejny nazor. Jen me napadlo, ze by se to dalo eventuelne vyuzit.
Schuzky bych zavedl povinne, pokud nekdo nebude schopen se dostavit neda se nic delat, ale mel by se  vzdy predem domluvit(omluvit) s managerem ten o tom urcite musi vedet, kdyz uz nikdo. Ale tak to je asi zrejme.

**Comment by ghost** [comment]
Hlavne ne facebook, sice nabizi hodne funkcionality ale ma svy proti, GitHub bude v dokumentaci znit lepe.

Sprava issues, milniku a diskuze tymu: www.github.com
terminy: www.doodle.com
absolutne souhlasim

Schuzky byl dal povinne, jedina vyjimka - zduvodnena omluva. Schuzky bych bral jako zamestnani - kdyz se rekne v 10hod schuzka, musime tam byt v 10hod. A kdyz nemuzete nebo jste nemocni, predevsim se predem omluvit at se muze s tim posleze pocitat...

**Comment by KratochvilJiri** [comment]
Uzavřeno. Použivá se email, gitHub, skype a mob. telefony.
