### ISSUE TITLE
Dokument - Návrh

### ISSUE THREAD

**Issue by KratochvilJiri** [FilipMatys/MPR2015#21]
Dokument vypracuje a zodpovida za něj @FilipMatys. Jeho úkolem je zejména vypracování návrhu GUI, zbylou práci rozdělí rovnoměrně mezi členy programového týmu na základě domluvy.

Kostra k dokumentu je v zadání projektu.

Průběh návrhu bude @FilipMatys reportovat a konzultovat mně.

Dokument bude vypracován dokonce víkendu/půlky následujícího týdne.

**Comment by FilipMatys** [comment]
Pripraven navrh GUI. Po schuzi bude doplneno o textove popisy a vlozeno do dokumentu.

**Comment by KratochvilJiri** [comment]
Vypadá to dobře! Kdyžtak někam nasdílej to pdf pro ostatní. Díky.

**Comment by FilipMatys** [comment]
Ok, je to tam. Sklad dokumentu/ostatni

**Comment by FilipMatys** [comment]
Bylo vytvořeno několik issue k danému dokumentu. Mnoho toho vychází z návrhu a specifikace, k jinému bude potřeba znát diagram tříd. Pokud budete cokoliv potřebovat, tak se na mě obraťte. Pokud víte, že nestíháte, tak ,prosím, dejte vědět. Já mám v plánu během zítřejšího dne dodělat popis k návrhu GUI, takže bych měl být stále na příjmu.

Poprosím všechny, aby během středy ke svému issue napsali, jak jste na tom. V opačném případě Vás budu kontaktovat.

Děkuji

**Comment by KratochvilJiri** [comment]
Do čtvrteční schůze by měly být vypracovány alespoň beta verze všech úkolů (tak jak psal Filip v jednotlivych issues), abychom případné nejasnosti mohli prodiskutovat ve větším počtu lidí. Na druhou stranu neměl by to být jen nějaký prvnotní nástřel, který budeme muset salodlouze analyzovat a z větší části přepracovávat. Mělo by to mít hlavu a patu, jinými slovy logickou stavbu a smysl a co možná nejlépe odpovídat Specifikaci. Určitě podávejte report o tom jak na tom jste a pokud si nebudete vědět rady/nebudete si jistí/nebudete stíhat ozvěte se co nejdříve ať to můžeme řešit!

Předběžný plán je takový, že ve čtvrtek prodiskutujeme a doladíme nutné věcí a v pátek se dokončí jednotlivé issue a zapracují se do dokumentu a ten bude připraven ke schvalení. V pondělí/uterý (pokud budou mít zákazníci čas) prezentujeme zákazníkům.

**Comment by FilipMatys** [comment]
Predbezne rozepsany navrh je v datovem skladu. Jakmile budu mit dnes zac cas, tak budu pokracovat.

**Comment by FilipMatys** [comment]
Doplneno o obrazovku pro spravu vyjimek. Dale upraveny nektere mockups, pridana sitemap a paleta pro vysledny produkt.

**Comment by S1LL** [comment]
Ještě takový detail co jsem zapomněl, poznámky na speciální služby bude taky pod položkou notes? Například typ poznámky?

**Comment by FilipMatys** [comment]
Jj, o tom padla rec pak v druhe casti schuze. Zapracuji to do navrhu a dam vedet

**Comment by FilipMatys** [comment]
Speciální požadavky firmy jsem zapracoval do návrhu. Díky za připomínku. 

Nahrána verze s popisy a doplněno o obrázky. Není u nich zatím legenda, bude doplněno, až budeme vše dávat dohromady.

Poprosím členy týmu, kteří si najdou čas a náladu, o kritiku.

Díky

**Comment by FilipMatys** [comment]
Poprosím všechny, aby do osmé hodiny dali vědět, jak jsou na tom. 

Pokud jste se k tomu doposud nedostali, tak nevadi. Pokud někdo narazí na problém, tak jsem k dispozici (se zpožděním). Mimo jiné je k dipozici i Vojta jako pracovní síla.

Díky

**Comment by FilipMatys** [comment]
Doplněn návrh GUI o popisek filtrů a zároveň doplněny chybějící tlačítka a jejich popisky.

**Comment by FilipMatys** [comment]
Návrh je po úpravě diagramu tříd nyní ve složce schváleno ve formátu docx

**Comment by KratochvilJiri** [comment]
Fajn. Návrh bych tedy uzavřel, pokud budou probíhat ještě nějaké další změny. Můžeme ho zpětně otevřít, ať se nám tady teď nemotá.
