### ISSUE TITLE
Dokument - Zápis z 2. schůze se zákazníkem

### ISSUE THREAD

**Issue by KratochvilJiri** [FilipMatys/MPR2015#22]
Vypracovat dokonce týdne zápis z dnešní schůze.

**Comment by andreamarcelyova** [comment]
Zapis je v datovom sklade - schuze-zaznamy/externi. Snad som tam na nic moc nezabudla.

**Comment by KratochvilJiri** [comment]
Dobra práce. Schvaleno.
