### ISSUE TITLE
Návrh - Specifikace uživatelských testů

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#24]
Poprosím Tě o vypracování části návrhu, a to Specifikace uživatelských testů. Pokud budeš potřebovat, tak @andreamarcelyova by Ti měla být k dispozici.

Na schůzi bychom měli probrat alespoň beta verzi návrhu, tudíž poprosím o prvotní vypracování do čtvrteční schůze 9.4.2015.

**Comment by S1LL** [comment]
Nahrána první verze, možná zítra dodělávky :smiley_cat:

**Comment by FilipMatys** [comment]
Velmi dobře, díky! Jen nezapomínej na spánek :/ Ikdyž věřím, čas se teď těžko hledá

**Comment by S1LL** [comment]
Rozsáhlejší korekce kroků u testů + pár nových testů... nový soubor ve skladě

**Comment by FilipMatys** [comment]
Děkuji
