### ISSUE TITLE
Návrh - Diagram užití

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#26]
Poprosím Tě o vypracování části návrhu, a to Diagram užití. 

Na schůzi bychom měli probrat alespoň beta verzi návrhu, tudíž poprosím o prvotní vypracování do čtvrteční schůze 9.4.2015.

Vycházej ze specifikace a návrhu. Pokud budeš mít jakékoliv dotazy, tak se na mě obrať. Návrh je zatím ve formě PDF ve skladu dokumentů.

**Comment by FilipMatys** [comment]
Čau Honzo, můžeme s Tebou počítat? Nemáme od Tebe žádnou zpětnou vazbu

**Comment by jlorenc01** [comment]
Diagram mám načrtnutý na papíře. Během dneška ho překreslím v nějakém nástroji a nahraju do skladu dokumentů.

**Comment by FilipMatys** [comment]
Super, díky. Ještě, prosím, nezapomeň, že zítra máme schůzi.

**Comment by FilipMatys** [comment]
Čau Honzo,
Kdy asi můžu očekávat, že nahraješ diagramy do datového skladu? Kolik jsi toho stihl?

**Comment by jlorenc01** [comment]
Nahrál jsem první verzi.

**Comment by FilipMatys** [comment]
Supr, diky

**Comment by FilipMatys** [comment]
Ahoj Honzo,

Jak pokračují práce? Narazil jsi na nějaký problém?

**Comment by jlorenc01** [comment]
Nová verze.

**Comment by FilipMatys** [comment]
Poprosím o "tiché" odebrání Use VyhledatFirmy pro roli Firma, děkuji

**Comment by jlorenc01** [comment]
Ok.

**Comment by FilipMatys** [comment]
Poprosím příště o informování, že změna proběhla. Děkuji (i za tu změnu)

**Comment by jlorenc01** [comment]
No tou předchozí zprávou jsem měl na mysli, že změna byla provedena. Ale máš pravdu, příště to uvedu explicitně.

**Comment by FilipMatys** [comment]
Poprosím ještě z Firma odebrat ZobrazitSeznamFirem, děkuji,

Výsledek poprosím ve formátu PNG, díky

**Comment by FilipMatys** [comment]
Muzu dnes ocekavat zmeny? Dekuji

**Comment by jlorenc01** [comment]
Změny nahrány. Jen je třeba do výsledného dokumentu přepsat ty 2 poznámky z use_case.pdf (nejsou součástí obrázku, use_case.pdf je dokument vysázený v Latexu).

P.S. Omlouvám se za zpoždění, venku bylo hezky.

**Comment by FilipMatys** [comment]
Supr, díky
