### ISSUE TITLE
Návrh - Sekvenční diagram/Diagram spolupráce

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#27]
Poprosím Tě o vypracování části návrhu, a to sekvenční diagram, nebo diagram spolupráce.

Na schůzi bychom měli probrat alespoň beta verzi návrhu, tudíž poprosím o prvotní vypracování do čtvrteční schůze 9.4.2015.

Vycházej ze specifikace a návrhu. Pokud budeš mít jakékoliv dotazy, tak se na mě obrať. Návrh je zatím ve formě PDF ve skladu dokumentů.

**Comment by azuritus** [comment]
Vytvořil jsem pracovní verzi několika sekvenčních diagramů a umístil je do datového skladu.

**Comment by FilipMatys** [comment]
Vypadá to velice dobře, dobrá práce a díky za info.

**Comment by KratochvilJiri** [comment]
Jak to vypadá s finální verzí prosimtě?

**Comment by azuritus** [comment]
Aktualizoval jsem diagram podle aktuální verze diagramu tříd a vložil ho do datového skladu. Pokud nebudou připomínky a/nebo významné změny v diagramu tříd, považoval bych tuto verzi za finální.

**Comment by FilipMatys** [comment]
Supr, diky moc

**Comment by FilipMatys** [comment]
Děkuji za sekvenční diagramy. S tím, co je vytvořeno, si vystačíme.
