### ISSUE TITLE
Dokument - zápis z 2. schůze programového týmu

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#28]

**Comment by andreamarcelyova** [comment]
Zapis najdete v datovom sklade. Mimochodom, Filip, len taky detail, vsimla som si, ze v navrhu - 3.9 Seznam výjimek chyba popis tlacitka Delete, o ktorom bola rec na schodzke.

**Comment by FilipMatys** [comment]
Ok dakujem, mam napisane a doplnim ked sa k tomu dostanem.

**Comment by KratochvilJiri** [comment]
Schváleno, uzavřeno.
