### ISSUE TITLE
3. Schůze se zákazníkem - schvalení Návrhu

### ISSUE THREAD

**Issue by KratochvilJiri** [FilipMatys/MPR2015#29]
Dnes v 16:00 v C236 proběhne 3.schůze se zákazníkem za účelem schválení návrhu. 
Potencionální účastniky schůze jsem již kontaktoval prostřednictvím telefonu jedná se o: @FilipMatys, @andreamarcelyova, @LiborMan.

**Comment by andreamarcelyova** [comment]
Zaznam o schodzke je v datovom sklade, pozrite sa potom na to, nie som si uplne ista ci to malo byt takto a ci je tam vsetko..

**Comment by KratochvilJiri** [comment]
Co se struktury dokumentu a obsahu týká, tak z toho co říkal asistent to stačí. Jen tu mám tři poznámky. 

1)
Pochopil jsem to tak, že obdržen částka se má přejmenovat na příslíbenou a zároveň přidat flag zaplaceno/nezaplaceno. Takže pokud nejsu vedle a souhlasí s tím i ostatní, tak to tam prosím připiš.

2)
Říkal, že by bylo dobré vytvořit metriky projektu před započetím implementace. Takže to bych tam taky zmínil, že to bude vypracované teď někdy.

3)
Diskutovali jsme tam, jak se chovat při mazáni konferencí a nevím jestli je to někde přesně definováno. On navrhoval buď mazání všeho (tzn. celková provázanost) nebo nastavování flagu u všeho a poté nastavení viditelnosti/neviditelnosti v systému podle flagu. Ja bych to videl, tak že ukončené konference není možné mazat a je možné mazat pouze ty budoucí s tím, že se smaže i vše okolo. Poprosím opět o reakci ostatních a zapracování do záznamu.

**Comment by FilipMatys** [comment]
3)
Z mého pohledu hodně závislé na požadavku klienta. Na schůzi se s námi bavil spíše jako asistent. 

Chápal bych mazání konference jako totální, tedy její kompletní smazání včetně všech vazeb (přílohy + účasti + účastnící) a to z toho důvodu, aby bylo uvolněno místo na disku. 

Souhlasím ale s návrhem umožnit mazání pouze zatím neaktivních konferencí. Původně to tak bylo zamýšleno

**Comment by KratochvilJiri** [comment]
3) Tedy, tak jak jsem psal výše ano? Pokud, nikdo nevznese nějakou námitku do zítra odpoledne. Poprosím o zapracování tohoto bodu do zápisu. Mazání pouze neaktivních a neuzavřených konferencí včetně všech návazností.

**Comment by KratochvilJiri** [comment]
Uzavřeno.
