### ISSUE TITLE
Obrazovka: Participations

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#31]
Spolu s obrazovkou vytvoř i entitu Participations

**Comment by jlorenc01** [comment]
Chybí zatím odvozené atributy (issue #50). U atributu ExpectedPayment jsem změnil datový typ z Decimal na String, aby bylo možné zadat rozmezí.

**Comment by FilipMatys** [comment]
Diky.

Jinak proc rozmezi? Zadavat rozmezi by se melo pouze u filtru, castka by mela zustat decimal. Pokud tedy myslime na to same

**Comment by jlorenc01** [comment]
Asi jsem se v dokumentu podíval na špatný řádek (sekci k filtrování). V příštím commitu opravím.

**Comment by FilipMatys** [comment]
Poprosím o dokončení, děkuji. Odvozené atributy ukládat do databáze.

**Comment by FilipMatys** [comment]
Opět mi chybí zpětná vazba

**Comment by jlorenc01** [comment]
"Odvozené" atributy ukládány do databáze, přidány filtry dle těchto atributů.

**Comment by FilipMatys** [comment]
Co zbývá, prosím?

**Comment by jlorenc01** [comment]
Asi kompletní.
