### ISSUE TITLE
Obrazovka: Companies

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#32]
Spolu s obrazovkou vytvoř i entitu Company

**Comment by FilipMatys** [comment]
Co zbývá, prosím?

**Comment by Lorry1** [comment]
Při odstranění firmy ze systému chci odstranit uživatele typu firma. To funguje ok, nicméně po odstranění jsem přesměrován na seznam firem a řádek s právě odstraněnou firmou je pořád v tabulce (pouze atributy uložené v tabulce firma). Asi způsobeno tím, že se odstraní uživatel typu firma, pak dojde k přesměrování na seznam firem a teprve potom se spustí cascade delete, který odstraní firmu atd. Je nutné aktualizovat stránku F5, pak je to v pořádku.

**Comment by FilipMatys** [comment]
Ať už zbývá cokoliv, bude v nových issues...
