### ISSUE TITLE
Obrazovka: Conference settings

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#35]
Vytvoř obrazovku pro nastavení konference. Upload souborů zatím neřeš. Společně s obrazovkou vytvoř i entitu Conference

**Comment by xlenga01** [comment]
Vytvoreny screeny pro "List konferenci" a "Nastaveni konference" - zatim se jedna o nastrely, je treba dodelat par drobnosti a prodiskutovat jak realizovat zobrazeni deadlinu.

**Comment by FilipMatys** [comment]
Diky.

Co mas na mysli "zobrazenim deadlinu"?

Poprosim o dodrzovani formatu zprav commitu. #cislo_issue a kratky popis. Popis chapej spis jako o co slo, detailnejsi popisek sem. Tak, jak jsi napsal :)

**Comment by xlenga01** [comment]
Opravil jsem par detailu a pridal natvrdo elementy do zalozky "Dates" - zatim tam neni zadny databinding(nevim jak to v LS udelat, obavam se, ze to bude nutne natvrdo pres kod)

**Comment by xlenga01** [comment]
uploadnul jsem verzi s deadlinama - bohuzel se objevilo nekolik problemu, ktere se mi ani po dost dlouhe dobe nepodarilo vyresit, takze jsem provizorne dal vsechny info o deadlinech do tabulky Conference - pokud zbyde cas, tak se to muze udelat pozdeji tak jak je to v navrhu, ale upozornuji, ze to pravdepodobne zabere dost casu(pokud mi tedy neunikl nejaky opravdu zasadni detail). Kazdopadne vzhledem k tomu, ze tabulka deadlines je navazana jen na Konferenci, tak by to nemelo nicemu vadit a melo by to byt funkcni

**Comment by FilipMatys** [comment]
Konzultoval jsi problém i s někým jiným?

**Comment by xlenga01** [comment]
Ptal jsem se Pavla, ale k nicemu jsme se nedostali...

**Comment by FilipMatys** [comment]
Ok. Můžeme tedy aktuální implementaci považovat za Resolved?

**Comment by xlenga01** [comment]
Co se tyce funkcnosti, tak by tam melo byt vsechno...  
- jen nejsou resena tlacitka co maj byt dole - tos mi rikal, at zatim neresim

**Comment by FilipMatys** [comment]
Ok, díky. Budeme řešit tehdy, jakmile budeme dávat dohromady aplikační logiku.

**Comment by FilipMatys** [comment]
Poprosím o odebrání nepotřebného kódu. Dávejte si, prosím, na to pozor. Může se to stát každému, ale stávat by se to nemělo. Své změny vždy kontrolujte před commitnutím, aby tam bylo opravdu to, co má být.

Jedná se o soubory:
\DataSources\ApplicationData\Conference.lsml.cs
\DataSources\ApplicationData_ApplicationDataService.lsml.cs

Děkuji

**Comment by xlenga01** [comment]
done and pulled, moje chyba(mel jsem dojem, ze jsem vsechny zmeny z toho, kdyz jsem si s tim hral discartnul - krome techle dvou veci vsechno ostatni zmizelo...), kazdopadne sry a dik za upozorneni

**Comment by FilipMatys** [comment]
Zavírám, dodělávky v issues
