### ISSUE TITLE
Obrazovka: Exceptions

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#37]
Spolu s obrazovkou vytvoř entitu Exception

**Comment by FilipMatys** [comment]
Ahoj Honzo, jak jsou na tom filtry? Nezapomeň, že se nejedná Search, ale to Filter.

Díly

**Comment by jlorenc01** [comment]
Filtry doplněny. Chybí filtrování dle odvozených atributů, protože je zatím neukládáme do databáze.

Dále asi bude problém s filtrováním podle těch výčtových atributů (Participation.State, User.Role apod.). Žádný multiple select apod. LS nenabízí. Zatím jsem nenašel žádné řešení.

**Comment by FilipMatys** [comment]
Je možné filtrovat alespoň podle jedné hodnoty? Tzn jednoduchý select?

**Comment by FilipMatys** [comment]
Poprosím o odpověď, děkuji

**Comment by jlorenc01** [comment]
Zkusil jsem si s tím hrát, ale zatím bez úspěchu. S použitím lookup table by ten jednoduchý šel určitě (stavy by byly v databázi v jiné tabulce). S tím choice listem nevím, ještě na to kouknu.

**Comment by FilipMatys** [comment]
Jak jsi na tom, prosím? Daří se Ti nějak pokročit?

**Comment by jlorenc01** [comment]
Jednoduchý select implementován.

**Comment by jlorenc01** [comment]
"Odvozené" atributy ukládány do databáze, přidány filtry dle těchto atributů.

**Comment by jlorenc01** [comment]
Přidáno tlačítko delete.
