### ISSUE TITLE
Datový model

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#38]
Vytvoreni datoveho modelu podle class diagramu

**Comment by jlorenc01** [comment]
Poznámky:

Atributy:

Date - rezervované slovo, nelze použít pro názvy atributů, přejmenoval jsem
Výčtový typ - není, použil jsem String/Choice List..., konzultováno s Pavlem
Attachement.Data - typ Binary
User.Email - použil jsem Email Address místo String
User.Phone - String, existuje tam typ Phone Number, ale asi s US formáty
Conference.GoldMin, ... - zatím jsem nechal double, ale je tam typ Money

Většina atributů je povinných. Nepovinné: Participation.numAttendee, Participation.specialRequests, Company.link, Company.description, Conference.Description, Deadline.description

Vazby: 

On Delete Behavior - Restricted(pokud jsou související data, nelze odstranit - např. pokud existují Participations, nelze odstranit Conference) nebo Cascade Delete (odstraní i související data - např. smazání Participation odstraní Exceptions, Attachements atd.) - zatím jsem dával všude Delete Cascade, i když někde bych si uměl představit Restricted

User(1) to Company(0..1) - lze pouze Cascade delete - tzn. odstranění uživatele odstraní ze systému firmu (potenciální problém)

User(M) to Participation(N) - přidána tabulka UserParticipation pro rozdělení M:N

**Comment by FilipMatys** [comment]
Super, diky.

Ad Conference.GoldMin)
Pavel zmiňoval, že na peněžní částky se hodí decimal, takže pokud je tam ten, tak bych ho tam využil.

Ad User(1) to Company(0..1)
Počítal bych s tím, že s uživatelem se odebere firma. Osobně nepovažuji za problém, proto za mě cascade

Ad User(M) to Participation(N))
Supr, to jsem chtěl navrhnout. Jedná se o vazbu Kontaktní osoba - Účast

**Comment by jlorenc01** [comment]
Money je založen na Decimal, tzn. dal jsem tedy zatím typ Money, currencyCode: Kč.

U všech stringů je zatím implicitní délka (255).
