### ISSUE TITLE
Navržení sledovaných metrik

### ISSUE THREAD

**Issue by KratochvilJiri** [FilipMatys/MPR2015#39]
Navrhni alespoň 10 metrik, které budou měřeny a hodnoceny na výsledném produktu.

Assistant zmiňoval, že by bylo dobré mít metriky před započetím implementace a měly by se k jednotlivým etapám. Mluvil i např. o metrice "komunikace" - četnost komunikace. Tak se prosím porozhlédni, co je možné vše měřit a zkus navrhnout nějaké metriky. Napíší ti k tomu ještě něco na skypu a v případě problému mě kontaktuj.

Stačí to v první části následujícího týdne.

**Comment by andreamarcelyova** [comment]
V datovom sklade - rozpracovano/metriky.txt je cca 12 metrik, inspiracia hlavne zo slajdov (5s_soft-metriky.pdf).

**Comment by KratochvilJiri** [comment]
Vypada to fajn jen budeme muset zaznamenávat výskyt chyby a dobu řešení (asi v nějakém online dokumentu zase). Chyby v dokumentaci přesně nevím, co je tím myšleno. Jinak napadlo mě ještě pár věcí:
- počet provedených testů - evidoval by tester - @LiborMan 
- porovnání času ztraveného návrhem a všemi dokumenty vs. čas strávený samotnou implementací a testováním.
- zkušenosti týmu - člen - stupnice 1-10 - sám sebe ohodnotí v rámci návrhu a implementace. 1 - neznám vůbec nic, 10 - absolutní profesionál.

Kdyžtak poprosím o názor a případné doplnění. Díky.

**Comment by andreamarcelyova** [comment]
Jo, ten pocet provedenych testov mi tiez napadlo, ale zabudla som na to ked som to pisala. Doplnila som tam vsetko.

**Comment by KratochvilJiri** [comment]
Super diky. Uzavřeno.
