### ISSUE TITLE
Jméno týmu

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#4]
Poprosim, abychom se dohodli na nazvu naseho tymu. Dnes jsem cetl, ze by to melo byt vyrizeno do 19.2.2015, takze bohuzel neni prilis mnoho casu na diskuzi. 

Za kazdy prispevek a projev aktivity (samozrejme k tematu ;)) budu rad.

**Comment by KratochvilJiri** [comment]
No meli bychom se tedy zamyslet a nahodit nejake navrhy. 

Jinak asi jste si vsimli v zadani, ale jen pro uplnost: --Názvy týmů - jakkoli je dobré mít poutavý název, doporučuji vám být uvážliví ve výběru jména pro tým, neboť i podle něj (a při prvním setkání zejména podle něj) vás může zákazník hodnotit - a jak známo, první dojem je velmi důležitý. Citát: "Od firmy Chiméra bych si software tedy rozhodně nekoupil". Pokud bude mít učitel výhrady k názvu týmu, oznámí to vedoucímu týmu a název bude nutno změnit.--

Takze názvy by mely mit pravdepodobne alespon minimalni asociaci s vyslednym produktem.

**Comment by KratochvilJiri** [comment]
No ted nad tim premyslim a asociace tam asi byt vylozene nemusi jen by to asi nemelo byt uplne mimo misu respektive odrazujici.

**Comment by FilipMatys** [comment]
Ted me akorat napadlo, ze delame aplikaci pro Excel@FIT, tak proc se nejmenovat EXCEL? nebo ExcelIS

**Comment by xlenga01** [comment]
Dekuji jirimu za velmi inspirativni komentar a navrhuji, abychom she pojmenovali WACH we Aren't Chimera

**Comment by KratochvilJiri** [comment]
No vida staci inspirativni komentar a uz je tu diskuze :D ;].

**Comment by KratochvilJiri** [comment]
Dekuji za navrhy. Excel bych asi nebral, protoze mi to pripada divne se pojmenovat podle produktu zakaznika. 

Osobne me nic moc nenapada jen nejakou zkratku ze slov "master", "application" a hotovo. Pripadne "web" se da zakomponovat do nazvu, pokud budeme delat webovou aplikaci.

Mohl by kazdy do dnesniho vecera nahodit aspon dva nazvy co? Neco nadhodte, at je to klidne blbost, pokud to nebude uplny bullshit, muze z toho vzniknout neco zajimaveho.

**Comment by S1LL** [comment]
Nějaké blbosti co mě napadali :D 
Excelio
SkyIS
ExcelNT (excelent? Kappa)
Webaris
Webixo
ISaria
Webjam

Ne a ne něco solidního vymyslet :D

**Comment by KratochvilJiri** [comment]
Hezky! 
Dalsi blbosti, co me ted bleskly hlavou, kdyz jsem precetl ty tvoje.
FITApps, FITCrew, FITjam, FITers.

**Comment by ghost** [comment]
Volil bych klíčová slova jako: konference, komunikace, firma, simple, easy, web (pokud bude webova aplikace)

Jinak z predeslych jmen bych volil:
ExcelNT

**Comment by KratochvilJiri** [comment]
Na dnešní přednášce proběhlo mezi zúčastněnými hlasování o názvu týmu. 
Byly vybráni dva kandidáti: Excellent a FitEx. Tito kandidáti mají momentálně následující počet hlasů: Excellent: 2.5, FitEx: 1.5. ¨
Poprosil bych o hlasování zbylé členy týmu. Připadně ještě můžete navrhnout jiný název, který může být zařazen do hlasováni.
 Pokud dnes neproběhne žádná další aktivita na toto téma, bude zvolen název Excellent.

**Comment by S1LL** [comment]
Tak já hlasuju pro Excellent :)

**Comment by azuritus** [comment]
Jsem pro Excellent, je takový údernější :)

**Comment by andreamarcelyova** [comment]
Ano, Excellent! :)

**Comment by KratochvilJiri** [comment]
Zvoleno Excellent - přihlášeno - zapsáno ve WISu.
