### ISSUE TITLE
Konfigurační řízení

### ISSUE THREAD

**Issue by KratochvilJiri** [FilipMatys/MPR2015#40]
Vypracuj dokument Konfigurační řízení. Šablona je v zadání. Dokument by měl obsahovat následující body:

1) Úvod
2) Rozdělení kompetencí členů týmu (kdo co programuje) a jméno manažera fáze.
3) Popis vývojové platformy.
4) Jaké bude používáno softwarové vybavení (překladače editory, správa projektu, správa verzí, built nástroje), !! způsob zálohování !!.
5) Mechanizmy pro zajištění vzájemné komunikace aktuálních verzí, vzájemného vyloučení při přístupu k r/w kopiím, kde a kdy se bude systém sestavovat a jakým způsobem budou k dispozici kompletní zdrojové texty.
6) Mechanizmus zpracování požadavků na změny.
7) Popis štábní kultury používané pro zdrojové texty - záhlaví zdrojových souborů, popis typů/proměnných/funkcí, konvence jmen, způsob odsazování, ..

Vypracovat do 26.4.

**Comment by KratochvilJiri** [comment]
Jak to vypadá prosim tě? Říkala jsi, že jsi na tom již pracovala. Až bude nějaká první verze, tak ji prosím sdílej a kontaktuj mě. Díky.

**Comment by andreamarcelyova** [comment]
Dokument je v datovom sklade - rozpracovano. Potrebovala by som tam doplnit verziu MySQL (ak sa teda pouziva MySQL, ako bolo pisane v specifikacii) a ake nastroje okrem Visual Studia pouzivaju programatori (ak vobec).

**Comment by FilipMatys** [comment]
MySQL nepouzivame, pokud se opet nepletu. Na toto se asi zeptej Pavla, nebo nekoho z programoveho tymu.

**Comment by andreamarcelyova** [comment]
Tiez sa mi to moc nezdalo, nasla som to v specifikacii, ale teda co pouzivame? Pavel nevedel a ze sa mam opytat teba :D

**Comment by FilipMatys** [comment]
Ok xD Tak ja se vecer mrknu a dam vedet.

**Comment by jlorenc01** [comment]
Externí připojení k databázi zatím není definováno, pokud se nepletu.

Během vývoje se data automaticky ukládají do interní databáze LS (používá SQL Server LocalDB). Při nasazení aplikace lze zvolit libovolnou jinou verzi SQL Server, případně by mělo jít použít i něco jiného, třeba MySQL.

**Comment by KratochvilJiri** [comment]
Vypadá to fajn. Jen přeposlední kapitola, že zákazník má přístup k momentáním verzím a je s ním diskutováno jak moc se mu to libí či nikoliv a podle toho upravováno, to bych řekl, že je spíš takový nerealizovatelný výkřik... ale klidně to tam nech. 

Nerealizovatelné je to ze dvou důvodů - se zákazníkem se dost špatně komunikuje a my nestiháme respektive se neustále opožďují všechny práce a nedokážu si představit jak by to vypadalo, kdyby jsme měli ještě zapracovávat další požadavky zákazníka po shlednutí aktualní verze a konzultacích.

Poprosím o přesunutí do složky ke schválení. Tu databází nevím. Na tom Azure to běží na čem?

**Comment by FilipMatys** [comment]
Pokud mi to nikdo nevyvrati, tak bych to videl na Microsoft SQL Server 2012, popripade novejsi

**Comment by andreamarcelyova** [comment]
Databaza doplnena a dokument je v zlozke ke schvaleni.

**Comment by KratochvilJiri** [comment]
Schvaleno, poprosim o presunuti do slozky schvaleno. 
Uzavřeno.
