### ISSUE TITLE
Dokument - zápis ze 3. schůze se zákazníkem 

### ISSUE THREAD

**Issue by KratochvilJiri** [FilipMatys/MPR2015#42]
Vypracuj zápis ze 3. schůze se zákazníkem, kde byl projednáván Návrh aplikace.

Jen pro přehlednost přiřazuji zpětně.

**Comment by andreamarcelyova** [comment]
Zmeny som doplnila, snad uz je to teda vsetko, zaznam v datovom sklade.

**Comment by KratochvilJiri** [comment]
Fajn. Ve skladu dokumentu jsem soubor rovnou přejmenoval. Díky za opravy. Uzavřeno.
