### ISSUE TITLE
Obrazovka: Settings

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#43]
Tvým hlavním úkolem bude zvládnutí problematiky "dlaždic". Nemusíš řešit stylování této komponenty, připrav však její hrubou implementaci s odkazem na použitý zdroj, či popiš myšlenku, s jakou si komponentu vytvořil.

Dlaždice, nebo také Tile, by měla umožňovat:
- Vložení textu
- Vložení ikony
- Vložení nadpisu (ve své spodní části)

Jako nástřel můžeš použít:
http://blog.ofanitguy.com/2013/11/13/lightswitch-2013-modern-ui-menus/

Výslednou implementaci použij k vytvoření obrazovky Nastavení

**Comment by FilipMatys** [comment]
Čau Vojto. Narazil jsi na nějaký problém?

**Comment by FilipMatys** [comment]
Potřeboval bych vědět, jak jsi na tom, protože tato konkrétní věc začíná mít zpoždění už týden.

**Comment by FilipMatys** [comment]
Měním assignee na @azuritus Poprosím o potvrzení, děkuji. 

Prosím nezapomenout, že komponenta musí být schopná zobrazit data, která jsou v návrhu (Nástěnky).

Děkuji

**Comment by azuritus** [comment]
Ahoj, nakonec jsem zvolil řešení založené na http://janvanderhaegen.com/2014/10/06/lightswitch-ux-sharepoint-like-tiles/ kde jsou jednotlivé dlaždice reprezentovány pomocí tlačítek. Idea pro zobrazení dat v dalších nástěnkách je taková, že vytvoříme datový zdroj jako REST service pomocí WebAPI, podobně jako v http://blogs.msdn.com/b/lightswitch/archive/2013/04/22/create-dashboard-reports-with-lightswitch-webapi-and-serverapplicationcontext.aspx

**Comment by FilipMatys** [comment]
Ahoj,

Skvělé, díky :) Zítra to probereme. Během dneška, pokud si najdu čas, tak na to mrknu.

Ještě jednou díky. Po zítřku můžeme začat vytvářet dashboardy a slepovat to dohromady.

**Comment by FilipMatys** [comment]
Velmi dobře. Nastavení zavírám. Upravil jsem trochu styly a přidal potřebné ikony.

Děkuji
