### ISSUE TITLE
Vytvoření úvodního uživatele

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#47]
Poprosím, pokud je to možné, tak o vytvoření uživatele s právem admin při nasazení aplikace, pokud takový již neexistuje. 

Momentálně se díky absenci uživatele nedá na testovací instanci přihlásit.

**Comment by azuritus** [comment]
Výchozí uživatelský účet je možné vytvořit pomocí průvodce nasazením aplikace na záložce Security settings - Yes, create...

**Comment by FilipMatys** [comment]
Výborně, díky. Takže už tam vlastně je ^^
