### ISSUE TITLE
Obrazovka: Registrace (Public)

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#48]

**Comment by FilipMatys** [comment]
Měním assignee na @xlenga01

**Comment by azuritus** [comment]
Ahoj, po dohodě s Filipem si beru zpět. Mám už nějak namyšlenou integraci na správu uživatelů a myslím, že takto to bude efektivnější.

**Comment by FilipMatys** [comment]
Ahoj @azuritus 

Honza odebíral z Company duplikáty Phone a ContactPerson (Telefon a Kontaktní osoba firmy), které jsou už v entite User. Poprosím Tě o zapracování těchto změn. 

Pokud máš nějaké nesrovnalosti, tak se ozvi Honzovi.

Děkuji

**Comment by jlorenc01** [comment]
Zatím jsem je ještě neodebral, protože by pak nešla aplikace sestavit. Budou odebrány po vyřešení tohoto issue.

**Comment by azuritus** [comment]
Registrační obrazovku jsem upravil tak, aby tyto atributy nevyužívala.
