### ISSUE TITLE
Cvičení

### ISSUE THREAD

**Issue by KratochvilJiri** [FilipMatys/MPR2015#5]
V rámci vyuky je naplánováno jedno bodované cvičení, které se má konat v průběhu pátého týdne a to bud v utery či ve čtvrtek v časech od 14:00 - 19:00 (trvat by mělo cca 2h).

Na přednášce jsme se shodli, že by nám vyhovoval termín čtvrtek 14:00. Poprosím o odsouhlasení zbylých členů týmů případně navržení jiného vyhovujícího termínu.

Na cvika se lze již zapisovat a to zatím pouze u doc. Kreslíkové. Pokud tedy chceme termín, na kterém se všichni shodneme, měli bychom se ji ozvat co nejdříve. Proto očekávám rychlou reakci. Díky.

**Comment by S1LL** [comment]
od 15 mám "povinnou" rétoriku :D ale tipuju že se nic nestane když tam nebudu

**Comment by azuritus** [comment]
Za mě je čtvrtek v pohodě.

**Comment by jlorenc01** [comment]
Souhlasím se čtvrtkem 14:00.

**Comment by andreamarcelyova** [comment]
Aj pre mna je stvrtok ok.

**Comment by KratochvilJiri** [comment]
Zapsán čtvrtek 14:00-15:50 - měli by jste to mít i ve WISu.
