### ISSUE TITLE
Zobrazování odvozených atributů

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#50]
Tutorial:
http://lightswitchhelpwebsite.com/Blog/tabid/61/EntryId/185/Computed-Properties-With-the-LightSwitch-HTML-Client.aspx

http://lobfactory.com/blog/?p=31
Tyka se:
IsPaid, Year, SponsorshipLevel

**Comment by FilipMatys** [comment]
Pozn.: Zvážit možnost/nutnost ukládat odvozené atributy do databáze, protože je nutné nad nimi umožnit filtrování.

**Comment by jlorenc01** [comment]
Abych to shrnul, v HTML Client nelze jednoduše zobrazit odvozené (computed) atributy na obrazovku (v Silverlight lze). Toto je možné obejít napsáním JS kódu pro výpočet atributu v PostRender Code (http://www.informit.com/articles/article.aspx?p=2087988&seqNum=8).

Nicméně dalším problémem je, že odvozený atribut nelze využít v dotazech, protože se do databáze neukládá (https://msdn.microsoft.com/en-us/library/ff851997.aspx).

Možnosti:

1) Ukládat odvozené atributy do databáze => duplicitní data
2) WCF RIA Services (blíže jsem zatím nestudoval):

https://social.msdn.microsoft.com/Forums/en-US/d2e04e57-b1e0-438e-9960-6551c144e886/cannot-create-a-query-using-a-computed-property?forum=lightswitchgeneral

https://msdn.microsoft.com/cs-cz/library/gg589479.aspx

http://lightswitchhelpwebsite.com/Blog/tabid/61/EntryId/52/Using-WCF-RIA-Services-In-LightSwitch-To-Simplify-Your-Application-UI.aspx

**Comment by FilipMatys** [comment]
Jedná se o problém, který jsme řešili na schůzi. Říkal jsi, že tomu dáš chvíli času. Pokud ten čas nemáš, nebo ho považuješ za zbytečný, tak použijeme záložní řešení a budeme atributy natvrdo ukládat do databáze --> Dej assignee na @Lorry1 

Děkuji

**Comment by azuritus** [comment]
Půl hodinky jsem nad tím laboroval, ale k žádnému rozumnému pokroku jsem nepřišel. Všechny popsané možnosti jsou dost náročné, takže bych asi zůstal u možnosti počítat hodnoty aplikační logikou a mít je uložené v databázi.

**Comment by FilipMatys** [comment]
Ok, díky. Poprosím tedy Honzu o implementaci

**Comment by jlorenc01** [comment]
Implementováno v rámci jiných issue.
