### ISSUE TITLE
Schůze programového týmu

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#51]
Ahoj,

Poprosil bych členy programového týmu o účast na schůzi. Programem bude:
- co se udělalo
- jaké jsou problémy
- zhodnocení stavu
- zhodnocení spokojenosti
- procesní záležitosti

Doodle:
http://doodle.com/akm56t5qr7t5phb2

Účast ostatních členů nepovažuji za nutnou, budou se řešit zejména technické věci.

Děkuji

**Comment by FilipMatys** [comment]
Schůze se uskuteční v 12:00 –14:00 v úterý, 28.4.2015.

**Comment by KratochvilJiri** [comment]
Schůze se konala, zápis se nachází v datovém skladu.
