### ISSUE TITLE
Mechanismus: Odkaz s parametry (Nastavení filtru, Select)

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#55]

**Comment by xlenga01** [comment]
ok, takze jak predat screenu parametry:
vypada to, ze moznosti je vic, ale ta zakladni je nasledujici:
mejme situaci, kdy z prehledu polozek (tabuka People) chceme poslat nejaky atribut (name) do addEditNewScreenu:

1, vlezu do addEditNewScreenu a vytvorim si novou datovou polozku("add Data Item", typ string), po vytvoreni v Properties zaskrtnu "is Parametr"
2, V prehledu pro People vytvorim tlacitko, donaviguju na addEditScreen, LS v dialogu pripravy seznam parametru - do textoveho pole vyplnim, co pres ten parametr chci predat(v nasem pripade tam bude neco jako "People.selectedItem.name")

pokud je muj popis spatne pochopitelny, tak je to popsano tady:
http://stackoverflow.com/questions/15269515/lightswitch-passing-data-from-one-screen-to-another
-jen tam neni ukazano, ze pri definovani tlacito ten LS automaticky pripravy ty parametry a co napsat do toho pole...

tady je jeste neco pro nastaveni defaultnich hodnot, ale je to v js(FUJ)
http://www.c-sharpcorner.com/UploadFile/dbd951/how-to-show-add-or-edit-screen-with-default-values-in-lights/
-PS :tohle jsem nezkousel...

**Comment by FilipMatys** [comment]
Díky. Nezapomeň si zalogovat práci

**Comment by FilipMatys** [comment]
Zavírám, vyřešeno
