### ISSUE TITLE
Mechanismus: Upload souborů

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#56]

**Comment by FilipMatys** [comment]
Dávám Honzovi pro řešení od zítřejšího dne.

**Comment by jlorenc01** [comment]
Nevím, kdy se k tomu dostanu. Potřebuju dělat na PRL a FLP.

**Comment by FilipMatys** [comment]
Tvůj časový fond platí?

**Comment by jlorenc01** [comment]
Existuje zase hodně step by step tutorialů pro Silverlight, ale málo pro HTML Client. Jako použitelné se mi zatím jeví

http://www.codeproject.com/Articles/580017/LightSwitch-HTML-Picture-Manager-Using-WCF-RIA-Ser

V tutorialu je upload obrázků, ale mělo by to být použitelné i s jinými typy souborů. Akorát je to zase přes WCF RIA Services.

**Comment by FilipMatys** [comment]
Dá se použít více možností:

Doinstalovat doplněk
http://blogs.msdn.com/b/bethmassi/archive/2012/11/22/building-an-html-client-for-a-lightswitch-solution-in-5-minutes.aspx

Web API:
http://blog.pragmaswitch.com/?p=1430

**Comment by jlorenc01** [comment]
http://blog.pragmaswitch.com/?p=1430 jsem pochopil, že není pro HTML Client.

http://blogs.msdn.com/b/bethmassi/archive/2012/11/22/building-an-html-client-for-a-lightswitch-solution-in-5-minutes.aspx Zde má zase Silverlight aplikaci a vkládá tam HTML Client aplikaci. My máme pouze HTML Client a přidáním tohoto bys měl 2 HTML Clienty, což teda asi možné je, ale nevím, jak to pak funguje.

EDIT: Tak to první by použitelné být mělo. Včera (vlastně už dnes) jsem nějak přehlédl odstavec Conclusion.

**Comment by azuritus** [comment]
Na základě #58 si přiřazuji.

**Comment by azuritus** [comment]
Implementováno. Nakonec jsem se vydal cestou popsanou v http://blogs.msdn.com/b/bethmassi/archive/2012/11/22/building-an-html-client-for-a-lightswitch-solution-in-5-minutes.aspx . Výsledek lze využít že v render Custom Control se přidá jeden řádek:

```
createImageUploader(element, contentItem, "max-width: 600px; max-height: 600px");
```

**Comment by FilipMatys** [comment]
Skvělé! Děkuji
