### ISSUE TITLE
Výjimka při pokusu o deploy

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#57]
![publish_exception](https://cloud.githubusercontent.com/assets/6004042/7387357/ba5295cc-ee5c-11e4-94cd-e1f23be69f3f.png)

**Comment by azuritus** [comment]
Narazil jsem na drobný problém s vlastním MembershipProviderem, takže jsem to nakonec musel vyřešit ne úplně pěkným způsobem, ale fungovat by to už mělo.

**Comment by FilipMatys** [comment]
Funkční, děkuji.
