### ISSUE TITLE
Obrazovka: Detail účasti na konferenci pro kontaktní osobu a admina

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#58]
Návrh: 4.16 Obrazovka detailu účasti na konferenci pro kontaktní osobu a admina

**Comment by xlenga01** [comment]
Ok, domluvili jsme se, ze tu mame psat co nejvic, takze davam vedet, ze ukol prebiram a zkusim zvladnout behem dneska. Az neco budu mit, dam vedet.

**Comment by xlenga01** [comment]
tak je nahozen prvni nastrel - zatim jsou tam dane alespon priblizne potrebne elementy 
- neresil jsem tlacitka, bude se tam muset pridelat nekolikrat spesl custom control a rendering js a pro nektere elementy je potreba predavani argumentu screenu a samozrejme prace se soubory....
  -dneska se na to este trochu mrknu, ale vzhledem k tomu, ze nejsou pripraveny formy pro vkladani dat, tak se to testuje dost tezko...

**Comment by FilipMatys** [comment]
Mrkni na https://github.com/FilipMatys/MPR2015/issues/56 a dodelej prosim obrazovku

**Comment by FilipMatys** [comment]
Poprosim, mrkni na upload souboru. Tomas se zatim pusti do detailu ze strany firmy. Dekuji

**Comment by azuritus** [comment]
Jdu na to, pokusím se dokončit.

**Comment by azuritus** [comment]
Dokončeno, kromě první záložky.

**Comment by azuritus** [comment]
Dokončena první záložka. Kvůli provedeným úpravám nebude nejspíš fungovat se starými definicemi konference.
