### ISSUE TITLE
Dashboard: Admin

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#59]

**Comment by FilipMatys** [comment]
Pokud máš čas se věnovat MPR, tak si můžeš převzít i WebAPI issue, který je Prec k tomuto issue. Děkuji

**Comment by azuritus** [comment]
Implementovány dlaždice a data do nich, zbývá dořešit funkčnost po stisku některých z nich (přechod na obrazovky s implicitním filtrem).

**Comment by FilipMatys** [comment]
Ok,děkuji. Předávám Tomovi, který měl na starosti zmíněný mechanismus.

**Comment by FilipMatys** [comment]
Dotaz:
Je možné přidat tlačítko vpravo nahoru? (Podobně, jako tlačítko Logout)

**Comment by FilipMatys** [comment]
Tlačítko vyřešeno
