### ISSUE TITLE
1. schůzka

### ISSUE THREAD

**Issue by KratochvilJiri** [FilipMatys/MPR2015#6]
Cílem schůzky bude:
1. seznámení členů týmů - ja osobně zatím viděl jen necelou půlku týmů
2. rozdělení rolí v týmů (mohou se v průběhu změnit)
3. pobavení se o projektu - kam ho budeme směrovat
4. rozdělení počátečních prací - pravděpodovně zatím pujde jen o uvodní studii a specifikaci
5. vytvorení dotazů na zakazníka

Poprosil bych vás všechny, aby jste si přečetli zadání projektu, co se implementace týká, abychom se o tom mohli pobavit. Díky. Odhaduji, ze bychom to mohli v rozmezí 45 - 90 min zvládnout.

Domlouvaní termínu: http://doodle.com/ts9gazu43qrm9in7#table

**Comment by FilipMatys** [comment]
Vyborne, dekujeme za program na schuzi. 

Jeste bych doporucil zalozit na wikipedii hlavicku Schuze se strankami pro kazdou schuzi, kde bude program schuze, datum uskutecneni a pote i zapis ze schuze k jednotlivym bodum. Spravu teto stranky bych delegoval. Klidne se toho ujmu osobne

**Comment by andreamarcelyova** [comment]
Za Pavla doplnim, ze je na horach cely tyzden, takze sa urcite nezucastni. (Internet im tam moc nefunguje, preto sa neozval.)

**Comment by azuritus** [comment]
Ahoj, tak už jsem přístup na ty internety získal, ale Andrejka má pravdu, zúčastnit schůzky se nebudu moci, protože z hor se vracím až v sobotu. Příští týden už budu plně k dispozici.

**Comment by KratochvilJiri** [comment]
Termin schuzky byl stanoven na stredu 11:30. 

Bude se konat v konferencni mistnosti c.1 v knihovne. 

Ti, kteri se nemuzou z nejakeho duvodu dostavit bych poprosil, aby me co nejdrive kontaktovali alespon na mail a napsali mi jake maji predstavy o sve vlastni praci na projekte tzn. jakou roli by radi plnili. Zkusim to zohlednit, ale nic neslibuji, pokud me nebudete kontaktovat ani se nedostavite. Budeme vam muset nejakou roli pridelit. 

U Pavla vim, ze je na horach, takze ten se zucastnit nemuze a Andrejce se omlouvam, ale neexistoval zadny termin, ktery odsouhlasili vsichni, takze jsem musel jeden zvolit.

Kontakt:
mail: xkrato17@stud.fit.vutbr.cz 
skype: krat4sek

**Comment by andreamarcelyova** [comment]
Nevadi, zajtra sa mi to sice nehodi, ale zariadim si to a budem tam.

**Comment by KratochvilJiri** [comment]
Super! Diky.

**Comment by KratochvilJiri** [comment]
Schůze proběhla v pořádku a projednali se všechny body. Díky za hojnou účast a aktivní diskuzi.
Záznam ze schůze by jste již nyní měli mít zpřístupněn na Google Drive.
