### ISSUE TITLE
Dashboard: Kontaktní osoba

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#60]

**Comment by FilipMatys** [comment]
Velmi podobně, jak dělal Pavel. Dej vědět, jak jsi na tom časově

**Comment by FilipMatys** [comment]
Nemám zpětnou vazbu, takže dávám Pavlovi

**Comment by azuritus** [comment]
Implementováno.

**Comment by FilipMatys** [comment]
Pavlíčku, došlo k záměně obrazovek.
ContactPersonDashboard Je potřeba přejmenovat na Company Dashboard, funkcionalita by měla odpovídat.

Je potřeba implementovat dashboard pro kontaktní osobu dle návrhu. (Velmi podobné adminovi)

**Comment by FilipMatys** [comment]
Poprosím o potvrzení převzetí úkolu, děkuji

**Comment by azuritus** [comment]
Implementováno. Tentokrát snad správná obrazovka :)

**Comment by FilipMatys** [comment]
Výborně, děkuji.
