### ISSUE TITLE
Dashboard: Firma

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#61]

**Comment by FilipMatys** [comment]
Větší objekt nahoře je vždy aktuální konference, ikdyž daná firma nemá zájem o účast. Rozkliknutí zatím neřeš, hlavně aby tam byla. Aplikační logiku pořešíme později.

Pod objektem aktuální konference je výčet minulých účastí firmy.

Vše dle návrhu, jen pro upřesnění.

**Comment by FilipMatys** [comment]
Předávám Vojtovi

**Comment by FilipMatys** [comment]
Prosím, v případě nedokončení mi zde chybí report, děkuji

**Comment by FilipMatys** [comment]
Jak to, prosím, vypadá?

**Comment by FilipMatys** [comment]
Dashboard už je implementován. Došlo k zaměnění obrazovek. Vypracováno @azuritus

**Comment by FilipMatys** [comment]
Přejmenováno a nastylováno pro úvodní dlaždici

**Comment by FilipMatys** [comment]
Poprosím o přejmenování, mě se to podařilo sbourat

**Comment by azuritus** [comment]
Přejmenováno. Omlouvám se za vyvolaný chaos.

**Comment by FilipMatys** [comment]
V pořádku, díky. Nakonec dobře, že je udělána právě dashboard firmy
