### ISSUE TITLE
HTTPS protokol pro excel@FIT prezentaci

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#63]
Momentálně naše aplikace běží nad https protokolem, přičemž zdrojové kódy pro stejnou funkcionalitu a vzhled jsou brány z původních stránek excel@FIT. Jejich web však nepodporuje protokol https, proto je jejich kód z naší strany blokován.

**Comment by FilipMatys** [comment]
Bude kontaktován p.Trchalík.

V případě, že nebude možné https na webu povolit, tak jako plán B:
- Stažení zdrojového kódu do aplikace

**Comment by KratochvilJiri** [comment]
Kontaktován dnes brzy ráno. Zatím bez odpovědi. Jelikož má dneska poslat informace k ukončení projektu, budeme doufat, že odpoví i na tuto otázku.

**Comment by KratochvilJiri** [comment]
Odpověď:

Dobry den,
bohuzel nemam vubec poneti, kdo to ma na starosti.
S pozdravem
Roman Trchalik

**Comment by FilipMatys** [comment]
Vyreseno stazenim zdrojovych kodu
