### ISSUE TITLE
Nelze vytvořit roli Firma

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#64]
Předpokládám, že se jedná o stejný problém, jako registrace.

![user_bug](https://cloud.githubusercontent.com/assets/6004042/7455732/fb7822d0-f27e-11e4-8e8a-6397c45ebcab.png)

**Comment by azuritus** [comment]
Vyřešeno odstraněním dotčených atributů z modelu.

**Comment by FilipMatys** [comment]
Zavírám, díky
