### ISSUE TITLE
Přesměrování na obrazovku role po přihlášení

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#66]
Po přihlášení uživatele je potřeba provést přesměrování na správnou obrazovku. Poprosím o implementaci.

Pozn.: Dashboard pro firmu má na starosti Vojta
https://github.com/FilipMatys/MPR2015/issues/61

Edit: Špatná reference

**Comment by azuritus** [comment]
Implementováno, na lokálním stroji nemusí fungovat úplně korektně, případně se na to ještě podívám večer.

**Comment by FilipMatys** [comment]
Po deployi se zobrazí Home stránka, která je prázdná, stejně tak lokálně. Vyzkoušeno pro admina i pro firmu po registraci.

**Comment by FilipMatys** [comment]
Oprava: Nefunguje pro firmu (Předpokládám ale, že bude doplněno po Vojtovi)
