### ISSUE TITLE
Dokument - referenční příručka

### ISSUE THREAD

**Issue by KratochvilJiri** [FilipMatys/MPR2015#67]
Jakmile to bude možné vypracuj dokument referenční příručka. Vzor je na public stránkách předmětu. V případě nejasností mě kontaktuj.

**Comment by FilipMatys** [comment]
Tome, už by si mohl začat.

Začni přihlášením, registrací a recover. Poté dashboardy, nastavení atd..

**Comment by KratochvilJiri** [comment]
Pracuje se již na dokumentu?

**Comment by xlenga01** [comment]
Teď začínám. Má to být na 4-10 stránk, takže tam toho zas až tolik nacpat nemužem. Osnovu beru odsud: http://www.fit.vutbr.cz/study/courses/MPR/public/pro-pra.html#prirucka 
- u nekterych veci si nejsem moc jisty co napsat(predevsim kapitola instalace)..., tak zatim udelam co budu moct a pak budu resit zbytek

Nenasel jsem zadny dobry priklad, pokud nahodou mate nekde neco schovaneho(pokud mozna primo k MPR), tak dejte vedet.

**Comment by KratochvilJiri** [comment]
Jo díky za info. Ty počty stran jsou celkem k ničemu u návrhu bylo něco podobného a měli jsme jich ale 40 a to jsem neměli zdaleko všechno. Na to moc neber zřetel, spíš sám zkus zhodnotit co by tam mělo být a jak se ti to bude dobře dělat. Na počet stran se stejně nikdo nedívá (alespoň doteď).

Jo udělej to podle te osnovy, ve vzorovém dokumentu je více méně to stejné.

Instalace se doplní.

Další info nemám. Ted jsem se snažil projít ještě stránky týmů, které to vypracovávali v minulých letech, ale žádné dostupné dokumenty jsem nenašel. Možná @andreamarcelyova se zmiňovala, že má nějakého kamaráda/kamarádku v jiném týmu. Takže kdyby bylo něco, co bychom neveděli jak se k tomu postavit, mohla by se eventuelně poptat.

**Comment by xlenga01** [comment]
nahodil jsem do skladu(rozpracováno) nástřel - ještě tam chybý informace v kapitole Instalace a v kapitola Referenční příručka je rozpracovaná - nevim přesně jak konkrétní tam mám být... Ještě mi chybý dva screeny, a některé z použitých nejsou úplně ideální, ale vzhledem k zbývajícímu času jsem je radši použil než nemít nic...

vždycky když tam něco chybý tak jsem se tam snažil psát TODO

**Comment by xlenga01** [comment]
Nahral jsem verzi, ktera by mela byt uz jaks taks stravitelna...

**Comment by KratochvilJiri** [comment]
Divám se, že už ji máš dokonce schvalenou od vedení..?? :D

Ted jsem to procházel. Koncepčně je to ok, ale není to kompletní. Nicméně rozsahem podle jejich měřítek je to ok a kdyby tam mělo být všechno tak to ma tak 30 stran aspon. Za další odkazuješ se tam na specifikaci a navrh, což je ok. Pokud někdo bude potřebovat, může si to dohledat tam. A poslední věc je zbytečné s tím ztrácet další čas. Bude lepší, když ještě něco naprogramuješ :). 

Za mě je to ok a dostačující. Poprosím o přesun do složky "ke schválení".

**Comment by KratochvilJiri** [comment]
Jo ještě jsem zapomněl. Kdyžtak to bleskově prolet. Narazil jsem tam na pár překlepů. Jeden byl přímo v popisu obrázku - obrázek 2. - presentation - popisek prvku.
