### ISSUE TITLE
Dokument - zápis z 3. schůze programového týmu 

### ISSUE THREAD

**Issue by KratochvilJiri** [FilipMatys/MPR2015#68]
Vypracuj zápis z 3. schůze programového týmu.

**Comment by KratochvilJiri** [comment]
Výpracováno, schváleno. Poprosím pouze o změnu řádku stav v uvodní tabulce dokumentu z rozpracováno na schváleno. Díky.

**Comment by ghost** [comment]
Radek aktualizovan...
