### ISSUE TITLE
Dokument - Definice problému

### ISSUE THREAD

**Issue by KratochvilJiri** [FilipMatys/MPR2015#7]
Vypracování prvního dokumentu - Definice problému.

**Comment by KratochvilJiri** [comment]
Dokument jsem napsal a zveřejnil na Google Drive. Poprosil bych alespoň @andreamarcelyova a @LiborMan, aby na to mrkli a případně doplnili/kontaktovali mě, jestli jsem na něco zapomněl a nebo odsouhlasili.

Zjisitl jsem, že v dokumentu má být ještě něco jako pohledy systému (jinak rečeno jednotlivé "stránky/views" aplikace), takže jsem se je pokusil doplnit.

Samozřejmě ocením jakoukoliv zpětnou vazbu klidně i z řad programátorů.

**Comment by S1LL** [comment]
Prosimtě, asi sem slepý, ale kde najdu odkaz na ty různé google drive dokumenty

**Comment by KratochvilJiri** [comment]
Posílal jsem vám všem pozvánku na školní mail. Nepřislo nic? Kdyžtak zkus tohle: https://drive.google.com/folderview?id=0BxzkpFaLnmdzc2VVRFdfYXVMX1k&usp=sharing_eid&invite=CI7iy8kL

Ale měli by jste to mít na mailech.

**Comment by S1LL** [comment]
Díky

**Comment by S1LL** [comment]
Je tam 3x stejná otázka. Je to myšleno pokaždé jinak? A já jiné otázky poznačené nemám.

**Comment by KratochvilJiri** [comment]
Opraveno. Nebyl to žádný zamer spis kombinace  "copy paste" a unavy. Jinak diky za feedback.

Co se tyka zakaznika kontaktoval jsem ho hned po schuzi, kdyz jsem dorazil domu. Odpoved prozatim zadna.

**Comment by KratochvilJiri** [comment]
Dokument považuji za schválený. Je k dispozici od čtvrtečního večera a nikdo další se k tomu nevýjadřil. Jelikož je zítra schůzka a nedávám velké šance, že by to někdo v neděli odpoledne ještě řešil, uzavíram to.

Jeden vytisk vezmu na schůzku se zákazníkem a budu do něj dělat poznámky. Bylo by dobré kdyby poznámky dělalo více lidí, ať se snížíme alespoň nějakým způsobem riziko v podobě pozdějších nejasností.

Kdyby se přeci jen někdo rozhodl, že dokument projde a chtěl by v něm něco změnit. Kontaktujte mne.

Poslední věc. Někam se zatoulala jedna verze dokumentu, takže jsem ještě pozměnil úvod, kam jsem zkopíroval zadání projektu, jinak by měl být dokument beze změn.
