### ISSUE TITLE
Tlačítko "Set as active" pro detail konference v nastavení

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#73]
Funkcionalita by měla být zřejmá z návrhu. Poprosím dnes o vyjádření, díky

**Comment by FilipMatys** [comment]
Poprosím i o "Set as close" a odstranění checkboxu, děkuji

**Comment by xlenga01** [comment]
Ok, mrknu dneska na to a uvidim co se da delat. Behem dneska este diztak napisu.

**Comment by FilipMatys** [comment]
Zavírám. Vzniklo nové issue jako bug
https://github.com/FilipMatys/MPR2015/issues/103
