### ISSUE TITLE
Odhad ceny produktu

### ISSUE THREAD

**Issue by KratochvilJiri** [FilipMatys/MPR2015#77]
Každý jste měli v rámci druhého úkolu vytvořit odhad ceny výsledného produktu k určitému datu. Jelikož tento vývoj má být prezentován na závěrečné obhajobě, vložtě všichni vaše odhady na google-drive. Vytvořil jsem tam složku "odhad-ceny".  Pokud možno to pojmenujte nacačátku datumem. Ja tám ted vložím svůj, takže budete mit vzor názvu souboru. Díky.

@azuritus @xlenga01 @FilipMatys @andreamarcelyova  @Lorry1 @Malajda @LiborMan

**Comment by FilipMatys** [comment]
Vypracováno a vloženo do skladu

**Comment by KratochvilJiri** [comment]
Vloženo od všech. Uzavřeno.
