### ISSUE TITLE
1. schůze s asistentem

### ISSUE THREAD

**Issue by KratochvilJiri** [FilipMatys/MPR2015#8]
Schůze za účelem prodiskutování Definice problému se zákazníkem.
Dnes kontaktuji asistenta (zákazníka) a termín bude upřesněn v následujících dnech.
Chůze se zůčastní @FilipMatys @KratochvilJiri @LiborMan @andreamarcelyova.

**Comment by KratochvilJiri** [comment]
Mně se osobně nehodí ani pondělí ani uterý v tomto čase... Tím pádem jsem pro ponděli, ať to mame co nejdřiv uzavřené a mužeme postupovat dal ke konečné specifikaci.

Dobry vecer,

bohuzel, dopoledne mi nepasuje. Navrhuji odpoledne mezi 14 a 16h (po, ut, ct).

S pozdravem
  Roman Trchalik

**Comment by S1LL** [comment]
Já klidně v pondělí 14-16

**Comment by FilipMatys** [comment]
Souhlasim s terminem pondeli 14-16

**Comment by andreamarcelyova** [comment]
Pondelok 14-16 moze byt

**Comment by KratochvilJiri** [comment]
Domluveno na pondělí 14:00 u pana Trchalíka v kabinetu. Zůčastnění nechť si projdou dokument, který bude sloužit jako podklad diskuze.

**Comment by KratochvilJiri** [comment]
Sraz 13:55 před: Kancelář C305.

**Comment by KratochvilJiri** [comment]
Schůze se úspěšně uskutečnila. Projdu si ještě jednou, co říkal a stanovím další plán. Poprosil bych vedouci dokumentace @andreamarcelyova, aby připravila zápis z této schůze. Vytvořím na to issue.

Tento issue je uzavřen.
