### ISSUE TITLE
Skusenosti - (seba)ohodnotenie

### ISSUE THREAD

**Issue by andreamarcelyova** [FilipMatys/MPR2015#80]
Povodne som to napisala do issue metriky, ale tam si to asi nikto neprecita, takze este raz:

Poprosim tychto clenov timu, aby sa ohodnotili od 1 do 10 podla toho ake maju skusenosti s oblastou, na ktorej pracovali v tomto projekte. Od 1 do 10. Idealne do zajtrajsieho vecera, ak nenapisete, bude vam pridelene nahodne hodnotenie. :)

F. Matys – programování
J. Lorenc – programování
V. Malášek – programování
T. Lengál – programování
L. Maňák – testování, specifikace

**Comment by FilipMatys** [comment]
Filip Matys - 6

**Comment by ghost** [comment]
Vojtech Malasek - 4

**Comment by jlorenc01** [comment]
C# - 1, Lightswitch - 1, Javascript - 6 => Ján Lorenc - 3
