### ISSUE TITLE
Obrazovka: Správa konferencí

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#81]

**Comment by xlenga01** [comment]
Delam na tom, behem dneska snad uzavru.

**Comment by xlenga01** [comment]
Pridelany labely a rozdeleno na activni konferenci a zbytek...

**Comment by FilipMatys** [comment]
Po uložení nefunguje korektně, jinak funguje správně. Pokud nepůjde jinak, vyřešíme čistě výpisem konferencí (bez dělení)
