### ISSUE TITLE
Zobrazení účasti pro firmu

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#82]
Jakmile se firma přihlásí, tak vidí aktuální konferenci. Je potřeba implementovat následující chování v závislosti na stavu:

1) Neexistuje žádná participation dané firmy s vazbou na aktivní konferenci
- Zobrazí se obrazovka pouze se záložkou About a tlačítkem Participate, po rozkliknutí se vytvoří objekt Participation s vazbou na přihlášenou firmu a aktuální konferenci.

2) Existuje vazba na participation dané firmy s vazbou na aktivní konferenci
- Po rozkliknutí se zobrazí detail účasti

Řešení je ponecháno na řešiteli.

**Comment by azuritus** [comment]
Implementováno.
