### ISSUE TITLE
Tlačítko "Add new company"

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#86]
Veškerá tlačítka v aplikaci, která jsou označena jako "Add new company" musí odkazovat na detail nového uživatele typu "Company", je tedy potřeba předávat parametry

**Comment by azuritus** [comment]
Implementováno na dashboarder admin a kontaktní osoba, jinde snad není.

**Comment by FilipMatys** [comment]
Ještě obrazovka Companies :)

**Comment by azuritus** [comment]
Doplněno.
