### ISSUE TITLE
Mizení aktivních dlaždic

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#89]
Po refreshi a po návratu zpět funguje. Pokud však dojde na kliknutí na Logo aplikace, tak dojde k přesměrování na Home bez aktivních dlaždic.

**Comment by azuritus** [comment]
Pokus o řešení, ale vzhledem k tomu, že lokálně jsem problém nedokázal reprodukovat ani na začátku, jedná se o střelbu naslepo.

**Comment by FilipMatys** [comment]
Opraveno, děkuji
