### ISSUE TITLE
1. Schůze programového týmu

### ISSUE THREAD

**Issue by KratochvilJiri** [FilipMatys/MPR2015#9]
Učel schůze je zvolení použitých technologií, rozdělení do týmu, předběžný náčrt prací.
Termín domluví vedoucí prográmátor @FilipMatys, který také vypracuje zápis se schůze.
Schůze se zůčastní @FilipMatys @Malajda @Lorry1 @azuritus @KratochvilJiri.

**Comment by FilipMatys** [comment]
Přikládám hlasování k termínu schůze:
http://doodle.com/fk2gmf2x363bn6ur

**Comment by FilipMatys** [comment]
Na programu schuze bude:
1. Probrat z implementacniho hlediska pozadavky zakaznika (bude dostupny zapis)
2. Zvolit vhodne implementacni prostredky
3. Zanalyzovat moznosti technickych pracovniku
4. Rozdeleni uvodnich praci

S terminem jeste pockame na @xlenga01

**Comment by FilipMatys** [comment]
Termin schuze stanoven na stredu od 11:30 v konferencni mistnosti c.1
