### ISSUE TITLE
Uživatel - Tlačítka "Participate.." a "Save and assign to me"

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#92]
Možnost účastnit se by měla být zobrazeno pouze při vytváření uživatele.

Podobně pak "Save and assign to me". Lze pouze pro kontaktní osobu ze strany FIT a pouze v případě, že se jedná o novou firmu a je zaškrtnuto výše zmíněné.

**Comment by azuritus** [comment]
Upraveno.
