### ISSUE TITLE
Uživatel - Participate in the upcoming event

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#93]
Po vytvoření firmy se zaškrtnutou možností je potřeba vytvořit objekt typu Participation s vazbou na aktuální konferenci a vytvořenou firmu.

**Comment by FilipMatys** [comment]
Platí pro registraci i pro vytvoření uživatele.

**Comment by FilipMatys** [comment]
Je možné, prosím, nastavit viditelnost podle toho, jestli je aktivní nějaká konference?

**Comment by azuritus** [comment]
Implementováno, včetně viditelnosti podle existence aktivní konference.
