### ISSUE TITLE
Unikátnost uživatelů

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#96]
I z důvodu recover password je nutné zajistit unikátnost uživatelů. Tato unikátnost by měla být zejména v uživatelském jméně a kontaktnímu emailu.

Další návrhy uvítám, avšak je nutné minimálně výše zmíněné.

**Comment by jlorenc01** [comment]
Bylo možné jednoduše zatrhnout checkbox Include in Unique Index v properties entity User, ale funguje jen s interní databází LS a vypisuje vlastní chybové hlášení. Zvolil jsem tedy custom validation. Zatím tedy pro atributy Login a Email.
