### ISSUE TITLE
Obrazovka: Participations - Add participation

### ISSUE THREAD

**Issue by FilipMatys** [FilipMatys/MPR2015#99]
Otevře dialogové okno, kde bude pouze:
- Výběr konference (Zobrazen rok)
- Výběr firmy (Zobrazeno jméno firmy)

Pro implementaci je potřeba nastavovat výchozí stav "Registered"

**Comment by FilipMatys** [comment]
Kdyby bylo možné, tak po uložení přesměrovat na detail dané účasti

**Comment by azuritus** [comment]
Implementováno, včetně přesměrování po uložení.
